// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYQPv4MIFlSGXKsOmvuQuxl0nlgU_44SI',
    appId: '1:467707584620:web:10b2237b56496e368cf849',
    messagingSenderId: '467707584620',
    projectId: 'note-app-f0b07',
    authDomain: 'note-app-f0b07.firebaseapp.com',
    storageBucket: 'note-app-f0b07.appspot.com',
    measurementId: 'G-XBZWD80355',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnXMqz2k18iG-s4lEHvtvTHPfisP1KjFc',
    appId: '1:467707584620:android:6bd4af8120b020c98cf849',
    messagingSenderId: '467707584620',
    projectId: 'note-app-f0b07',
    storageBucket: 'note-app-f0b07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-4tUrc5MEFMHg1PsjZfwpeHz9808rcE',
    appId: '1:467707584620:ios:b1b295f7a974d56b8cf849',
    messagingSenderId: '467707584620',
    projectId: 'note-app-f0b07',
    storageBucket: 'note-app-f0b07.appspot.com',
    iosClientId: '467707584620-rht7r4k2b463jqksju56iki1mgqadvgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectosFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3-4tUrc5MEFMHg1PsjZfwpeHz9808rcE',
    appId: '1:467707584620:ios:b1b295f7a974d56b8cf849',
    messagingSenderId: '467707584620',
    projectId: 'note-app-f0b07',
    storageBucket: 'note-app-f0b07.appspot.com',
    iosClientId: '467707584620-rht7r4k2b463jqksju56iki1mgqadvgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectosFlutter',
  );
}
